services:
  - type: web
    name: designportfolio-cms
    runtime: node
    plan: free
    buildCommand: npm install && npm run build -w apps/cms
    startCommand: npm run start -w apps/cms
    envVars:
      - key: NODE_VERSION
        value: "24"
      - key: DATABASE_URL
        sync: false
      - key: PAYLOAD_SECRET
        generateValue: true
      - key: WEB_APP_URL
        value: https://portfoliojacoboffenberg.netlify.app
      - key: R2_BUCKET
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_PUBLIC_URL
        sync: false
